services:
  actian-vectorai:
    image: actian/vectorai:latest
    container_name: ann-indexes-actian
    ports:
      - "6573:6573"
      - "6574:6574"
      - "6575:6575"
    restart: unless-stopped
    stop_grace_period: 2m
    environment:
      - ACCEPT_ACTIAN_VECTORAI_EULA=YES
      - ACTIAN_VECTORAI_ACCEPT_EULA=YES
